[[pages]]
path = "/"
screenshotTimestamp = "2026-04-13T16:55:39Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7428f8a7-3405-423c-a36c-694f24834f1a/b5abe84e-6958-4bde-b245-cb0e23776d46/GQxwYD5"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-04-11T10:21:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7428f8a7-3405-423c-a36c-694f24834f1a/b5abe84e-6958-4bde-b245-cb0e23776d46/JhNZZIn"

[[pages]]
path = "/register"
screenshotTimestamp = "2026-04-13T16:36:03Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7428f8a7-3405-423c-a36c-694f24834f1a/b5abe84e-6958-4bde-b245-cb0e23776d46/RqXmzlb"

[[pages]]
path = "/dashboard"
screenshotTimestamp = "2026-04-13T16:54:50Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7428f8a7-3405-423c-a36c-694f24834f1a/b5abe84e-6958-4bde-b245-cb0e23776d46/zGNjiRJ"
